/*
 * dice3d.c — procedural 3D polyhedron renderer.
 *
 * Fixed-point conventions:
 *   - Vertex coords live in int16_t with UNIT_FP (4096) representing 1.0.
 *     All polyhedra sit on a unit circumsphere, so coords are in
 *     [-UNIT_FP, +UNIT_FP].
 *   - sin_lookup / cos_lookup return [-TRIG_MAX_RATIO, +TRIG_MAX_RATIO]
 *     (= ±65536). After a rotation step we divide by TRIG_MAX_RATIO and
 *     fold back into int16_t.
 *
 * Screen coords:
 *   - 3D y is UP; Pebble screen y is DOWN. We negate y on projection.
 *   - 3D z is OUT of the screen toward the viewer.
 *
 * Culling and shading:
 *   - We compute the actual face plane normal via cross product of the
 *     first two edges. For D12 (regular dodecahedron), this matches the
 *     centroid direction, but for the D10 trapezohedron the kite faces
 *     are NOT symmetric around the polyhedron center — their centroids
 *     don't lie on the outward-normal axis — so centroid.z can disagree
 *     in sign with the actual normal.z. Using the real normal handles
 *     both polyhedra uniformly.
 *   - The cross-product normal's direction depends on vertex winding.
 *     We correct it by computing the dot product with the face centroid
 *     (which is guaranteed to be on the same side of origin as the
 *     outward direction, because the polyhedron is convex and centered
 *     at origin). If the dot is negative, the cross is pointing inward
 *     and we flip its sign.
 *   - After correction, n.z > 0 ⇔ face faces camera, and n · light is
 *     the lighting term.
 *
 * Winding (within faces):
 *   - Each face's vertices are listed in CCW order around the face's
 *     outward normal. gpath_draw_filled handles either winding for
 *     convex polygons identically, but the order must walk the
 *     perimeter — listing vertices that aren't adjacent on the face
 *     produces a self-intersecting polygon and visible gaps.
 *
 * Vertex / face tables for both polyhedra are generated by
 * tools/gen_dice.py. The script validates pentagon edge lengths, kite
 * planarity, opposite-pair value sums (D12), and perimeter ordering. Do
 * not hand-edit the tables; re-run the script.
 */

#include "dice3d.h"

#define UNIT_FP        4096   /* 1.0 in vertex fixed-point */
#define MAX_VERTS      20
#define MAX_FACE_VERTS 5

/* Numeral colors. Placeholders until the settings page lands — both the
 * resting color and the active-face highlight will be user-selectable
 * (along with the die body palette). For now: black on every face,
 * with the face whose label matches die->value tinted to make it read
 * as "this is the current time". */
#define COLOR_NUMERAL          GColorBlack
#define COLOR_NUMERAL_ACTIVE   PBL_IF_COLOR_ELSE(GColorDarkCandyAppleRed, GColorBlack)

typedef struct {
  int16_t x, y, z;
} Vec3;

typedef struct {
  uint8_t v[MAX_FACE_VERTS]; /* CCW vertex indices, viewed from outside */
  uint8_t n;                 /* 5 for pentagonal face, 4 for kite */
  int8_t  value;             /* baked numeral for this face */
} Face;

/* --- D12: regular dodecahedron ------------------------------------------ */

/* Vertex and face tables below are generated by tools/gen_dice.py. Do
 * NOT edit by hand — re-run the script if anything needs to change. The
 * script validates pentagon edge lengths, opposite-pair value sums, and
 * face-vertex CCW ordering. (The hand-maintained tables previously here
 * had a transposed vertex ordering on face value 8 — value-8 rendered as
 * a self-intersecting polygon at certain tumble angles, visible as
 * angular gaps in the silhouette.)
 *
 * Pre-rotation: each table is rotated so face 0's centroid sits at +z at
 * rest_x = rest_y = rest_z = 0. The D12 rotation is Ry(-31.7175°). The
 * D10 rotation is Rx(+54.1526°) then Ry(-48.1293°). For the D12 (regular
 * pentagon faces) centroid-alignment and normal-alignment coincide; for
 * the D10 (asymmetric kite faces) centroid-alignment keeps the face
 * center on the die center where the numeral lives. */
static const Vec3 d12_verts[20] = {
  {   768,  2365,  3255 }, /*  0 */
  {  3255,  2365,  -768 }, /*  1 */
  {   768, -2365,  3255 }, /*  2 */
  {  3255, -2365,  -768 }, /*  3 */
  { -3255,  2365,   768 }, /*  4 */
  {  -768,  2365, -3255 }, /*  5 */
  { -3255, -2365,   768 }, /*  6 */
  {  -768, -2365, -3255 }, /*  7 */
  { -2012,  1462,  3255 }, /*  8 */
  {  2012,  1462, -3255 }, /*  9 */
  { -2012, -1462,  3255 }, /* 10 */
  {  2012, -1462, -3255 }, /* 11 */
  {  1243,  3826,   768 }, /* 12 */
  {  1243, -3826,   768 }, /* 13 */
  { -1243,  3826,  -768 }, /* 14 */
  { -1243, -3826,  -768 }, /* 15 */
  {  2487,     0,  3255 }, /* 16 */
  {  4023,     0,   768 }, /* 17 */
  { -4023,     0,  -768 }, /* 18 */
  { -2487,     0, -3255 }, /* 19 */
};

static const Face d12_faces[12] = {
  { { 10,  2, 16,  0,  8 }, 5,  1 },
  { { 19,  5,  9, 11,  7 }, 5, 12 },
  { {  9,  1, 17,  3, 11 }, 5,  2 },
  { {  6, 10,  8,  4, 18 }, 5, 11 },
  { {  4,  8,  0, 12, 14 }, 5,  3 },
  { {  7, 11,  3, 13, 15 }, 5, 10 },
  { { 14, 12,  1,  9,  5 }, 5,  4 },
  { { 15, 13,  2, 10,  6 }, 5,  9 },
  { {  0, 16, 17,  1, 12 }, 5,  5 },
  { { 19,  7, 15,  6, 18 }, 5,  8 },
  { {  3, 17, 16,  2, 13 }, 5,  6 },
  { { 18,  4, 14,  5, 19 }, 5,  7 },
};

/* --- D10: pentagonal trapezohedron ------------------------------------- */
static const Vec3 d10_verts[12] = {
  { -1786, -3320,  1601 }, /*  0: top apex    */
  {  1786,  3320, -1601 }, /*  1: bottom apex */
  {  2530,  -351,  3202 }, /*  2: upper[0] */
  { -1687,  1918,  3202 }, /*  3: upper[1] */
  { -3833,  1052,  -989 }, /*  4: upper[2] */
  {  -943, -1753, -3580 }, /*  5: upper[3] */
  {  2990, -2619,  -989 }, /*  6: upper[4] */
  {   943,  1753,  3580 }, /*  7: lower[0] */
  { -2990,  2619,   989 }, /*  8: lower[1] */
  { -2530,   351, -3202 }, /*  9: lower[2] */
  {  1687, -1918, -3202 }, /* 10: lower[3] */
  {  3833, -1052,   989 }, /* 11: lower[4] */
};

static const Face d10_faces[10] = {
  { {  0,  2,  7,  3 }, 4, 0 },
  { {  0,  3,  8,  4 }, 4, 1 },
  { {  0,  4,  9,  5 }, 4, 2 },
  { {  5, 10,  6,  0 }, 4, 3 },
  { {  6, 11,  2,  0 }, 4, 4 },
  { {  8,  3,  7,  1 }, 4, 5 },
  { {  4,  8,  1,  9 }, 4, 6 },
  { {  9,  1, 10,  5 }, 4, 7 },
  { {  1, 11,  6, 10 }, 4, 8 },
  { {  1,  7,  2, 11 }, 4, 9 },
};

/* --- Per-value rest rotations ------------------------------------------- */

/* Indexed by die->value. Applied before the user's rot_x/y/z so the face
 * labeled die->value sits dead-on the camera at rest. Combined with
 * drawing every visible face's baked numeral, this makes the die look
 * like a real D12/D10 instead of a single front numeral that flickers.
 *
 * Order is Rx then Ry (matches rotate_vertex); no rz component — each
 * value lands at whatever orientation the shortest centroid-onto-z
 * rotation produces. Generated by tools/gen_dice.py. */
static const int32_t d12_value_rx[13] = {
        0, /* [ 0] unused (D12 values are 1..12) */
        0, /* [ 1] */
    32768, /* [ 2] */
    11335, /* [ 3] */
    21433, /* [ 4] */
     9032, /* [ 5] */
    56504, /* [ 6] */
    23736, /* [ 7] */
    41800, /* [ 8] */
    54201, /* [ 9] */
    44103, /* [10] */
        0, /* [11] */
    32768, /* [12] */
};
static const int32_t d12_value_ry[13] = {
        0, /* [ 0] */
        0, /* [ 1] */
    53988, /* [ 2] */
     2921, /* [ 3] */
    62615, /* [ 4] */
    57098, /* [ 5] */
    57098, /* [ 6] */
     8438, /* [ 7] */
     8438, /* [ 8] */
     2921, /* [ 9] */
    62615, /* [10] */
    11548, /* [11] */
        0, /* [12] */
};
static const int32_t d10_value_rx[10] = {
        0, /* [ 0] */
     4602, /* [ 1] */
    38365, /* [ 2] */
    43198, /* [ 3] */
    55195, /* [ 4] */
    10430, /* [ 5] */
    22427, /* [ 6] */
    32768, /* [ 7] */
    37370, /* [ 8] */
     5597, /* [ 9] */
};
static const int32_t d10_value_ry[10] = {
        0, /* [ 0] */
    11416, /* [ 1] */
     9412, /* [ 2] */
    63774, /* [ 3] */
    58113, /* [ 4] */
     1762, /* [ 5] */
     7423, /* [ 6] */
        0, /* [ 7] */
    54120, /* [ 8] */
    56124, /* [ 9] */
};

/* --- Math --------------------------------------------------------------- */

static Vec3 rotate_vertex(Vec3 v, int32_t rx, int32_t ry, int32_t rz) {
  /* Rx -> Ry -> Rz. Each step divides products of (int16 * trig) by
   * TRIG_MAX_RATIO to fold the result back into the [-UNIT_FP, +UNIT_FP]
   * range. */
  int32_t x = v.x, y = v.y, z = v.z;

  int32_t cosx = cos_lookup(rx);
  int32_t sinx = sin_lookup(rx);
  int32_t y1 = (cosx * y - sinx * z) / TRIG_MAX_RATIO;
  int32_t z1 = (sinx * y + cosx * z) / TRIG_MAX_RATIO;
  /* x1 = x; */

  int32_t cosy = cos_lookup(ry);
  int32_t siny = sin_lookup(ry);
  int32_t x2 = ( cosy * x + siny * z1) / TRIG_MAX_RATIO;
  int32_t z2 = (-siny * x + cosy * z1) / TRIG_MAX_RATIO;
  /* y2 = y1; */

  int32_t cosz = cos_lookup(rz);
  int32_t sinz = sin_lookup(rz);
  int32_t x3 = (cosz * x2 - sinz * y1) / TRIG_MAX_RATIO;
  int32_t y3 = (sinz * x2 + cosz * y1) / TRIG_MAX_RATIO;

  return (Vec3){ .x = (int16_t)x3, .y = (int16_t)y3, .z = (int16_t)z2 };
}

static GPoint project(Vec3 v, GPoint center, int16_t radius) {
  /* Orthographic projection. y axis flips: 3D-y-up → screen-y-down. */
  return GPoint(
    center.x + (int16_t)((int32_t)v.x * radius / UNIT_FP),
    center.y - (int16_t)((int32_t)v.y * radius / UNIT_FP));
}

/* Light direction: upper-left, slightly toward camera. (-0.6, 0.6, 0.5)
 * in our fixed-point scale (4096 = 1.0). Pebble screen has y-down, but
 * dice3d works in 3D-y-up space and flips on projection, so a face whose
 * outward normal leans (-x, +y, +z) is the one pointing at the light. */
#define LIGHT_X (-2458)
#define LIGHT_Y  (2458)
#define LIGHT_Z  (2048)

/* Shading is n · light with n the un-normalized face normal. All faces
 * of a given polyhedron are congruent (regular pentagons for D12,
 * congruent kites for D10), so |n| is constant per polyhedron and we
 * can threshold the dot product directly. Thresholds are wide enough
 * to land sensibly for both polyhedra without per-type tuning. */
static GColor shade_for_normal(int64_t bright) {
#if defined(PBL_COLOR)
  if (bright >  20000000000LL) return GColorWhite;
  if (bright >              0) return GColorLightGray;
  if (bright > -20000000000LL) return GColorWindsorTan;
  return GColorBulgarianRose;
#else
  return (bright > 0) ? GColorWhite : GColorLightGray;
#endif
}

/* --- Public draw -------------------------------------------------------- */

/* Per-value rest rotation lookup. Indexed by die->value with bounds-clamp
 * to keep the math safe if die->value ever drifts out of range. */
static void rest_rotation_for(const Die *die, int32_t *rx_out, int32_t *ry_out) {
  if (die->type == DIE_HOUR) {
    int v = die->value;
    if (v < 1) v = 1;
    if (v > 12) v = 12;
    *rx_out = d12_value_rx[v];
    *ry_out = d12_value_ry[v];
  } else {
    int v = die->value;
    if (v < 0) v = 0;
    if (v > 9) v = 9;
    *rx_out = d10_value_rx[v];
    *ry_out = d10_value_ry[v];
  }
}

void dice3d_draw(GContext *ctx, const Die *die) {
  const Vec3 *verts;
  const Face *faces;
  int n_verts, n_faces;

  if (die->type == DIE_HOUR) {
    verts   = d12_verts;
    faces   = d12_faces;
    n_verts = 20;
    n_faces = 12;
  } else {
    verts   = d10_verts;
    faces   = d10_faces;
    n_verts = 12;
    n_faces = 10;
  }

  /* Rest rotation puts the face labeled die->value dead-on. The user's
   * rot_x/y/z (tumble spin or shake wobble) layers on top. At progress=1
   * of a FULL/QUICK tumble the user rotation is an integer multiple of
   * TRIG_MAX_ANGLE, so the polyhedron lands back at the rest pose for the
   * current die->value. */
  int32_t rest_rx, rest_ry;
  rest_rotation_for(die, &rest_rx, &rest_ry);

  /* Transform & project all vertices once. Two-step rotation (rest then
   * user) — Euler-angle composition is not additive so we can't fold them
   * into a single rotate_vertex call. */
  Vec3   transformed[MAX_VERTS];
  GPoint projected  [MAX_VERTS];
  for (int i = 0; i < n_verts; i++) {
    Vec3 v = rotate_vertex(verts[i], rest_rx, rest_ry, 0);
    v = rotate_vertex(v, die->rot_x, die->rot_y, die->rot_z);
    transformed[i] = v;
    projected[i] = project(v, die->center, die->radius);
  }

  /* Walk faces: cull back-facing via real face normal, shade by n·light,
   * draw filled + outlined, then draw the face's baked numeral.
   *
   * Numeral visibility:
   *   - At rest (all rotation axes zero): only the face labeled
   *     die->value draws its numeral, with the prominent "active" font
   *     and the highlight color. Other visible faces stay blank — at
   *     small projected sizes their glyphs overflow into neighbour
   *     faces no matter how tight we make the box.
   *   - While rotating (any rot_x/y/z non-zero — physics throw, hour
   *     QUICK, minute SHAKE): every visible face draws its numeral
   *     using the smaller "side" font. The active face keeps the
   *     highlight color so you can see which value the die will settle
   *     on as it tumbles.
   * AREA_DOUBLE_MIN still culls near-edge-on slivers entirely. */
  #define AREA_DOUBLE_MIN 80
  bool is_rolling = (die->rot_x != 0 || die->rot_y != 0 || die->rot_z != 0);

  GColor  outline = GColorBlack;

  /* Two-tier glyph: the face labeled die->value (the time the user is
   * reading) gets the prominent font; every other visible face gets a
   * smaller "context" font and tighter box. The smaller side-face box
   * mirrors how a real die looks under perspective — distant faces
   * appear with smaller-looking numerals — and lets the side glyphs
   * fit inside the foreshortened side-face polygons without the
   * strict polygon cull. */
  GFont   font_active = (die->type == DIE_HOUR)
    ? fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD)
    : fonts_get_system_font(FONT_KEY_GOTHIC_14_BOLD);
  GFont   font_side   = fonts_get_system_font(FONT_KEY_GOTHIC_14_BOLD);

  int16_t box_active_w = (die->type == DIE_HOUR) ? 22 : 10;
  int16_t box_active_h = (die->type == DIE_HOUR) ? 16 : 12;
  int16_t box_side_w   = (die->type == DIE_HOUR) ? 12 :  8;
  int16_t box_side_h   = (die->type == DIE_HOUR) ? 11 : 10;

  for (int f = 0; f < n_faces; f++) {
    const Face *face = &faces[f];

    /* 3D centroid — used to ensure the cross-product normal points
     * outward, since the centroid is always on the same side of origin
     * as the outward-facing direction for a convex polyhedron centered
     * at origin. */
    int32_t cx = 0, cy = 0, cz = 0;
    for (int k = 0; k < face->n; k++) {
      cx += transformed[face->v[k]].x;
      cy += transformed[face->v[k]].y;
      cz += transformed[face->v[k]].z;
    }
    cx /= face->n;
    cy /= face->n;
    cz /= face->n;

    /* Face plane normal: cross product of two edges sharing vertex v[0]. */
    int32_t e1x = transformed[face->v[1]].x - transformed[face->v[0]].x;
    int32_t e1y = transformed[face->v[1]].y - transformed[face->v[0]].y;
    int32_t e1z = transformed[face->v[1]].z - transformed[face->v[0]].z;
    int32_t e2x = transformed[face->v[2]].x - transformed[face->v[0]].x;
    int32_t e2y = transformed[face->v[2]].y - transformed[face->v[0]].y;
    int32_t e2z = transformed[face->v[2]].z - transformed[face->v[0]].z;

    int32_t nx = e1y * e2z - e1z * e2y;
    int32_t ny = e1z * e2x - e1x * e2z;
    int32_t nz = e1x * e2y - e1y * e2x;

    /* Winding correction: flip if normal points inward. */
    int64_t outward = (int64_t)nx * cx + (int64_t)ny * cy + (int64_t)nz * cz;
    if (outward < 0) {
      nx = -nx; ny = -ny; nz = -nz;
    }

    /* Backface cull (true camera-facing test). */
    if (nz <= 0) continue;

    /* Sliver cull: projected 2D area via shoelace. */
    GPoint face_pts[MAX_FACE_VERTS];
    for (int k = 0; k < face->n; k++) face_pts[k] = projected[face->v[k]];
    int32_t area_2x = 0;
    for (int k = 0; k < face->n; k++) {
      GPoint a = face_pts[k];
      GPoint b = face_pts[(k + 1) % face->n];
      area_2x += (int32_t)a.x * b.y - (int32_t)b.x * a.y;
    }
    if (area_2x < 0) area_2x = -area_2x;
    if (area_2x < AREA_DOUBLE_MIN) continue;

    int64_t bright = (int64_t)nx * LIGHT_X
                   + (int64_t)ny * LIGHT_Y
                   + (int64_t)nz * LIGHT_Z;
    GColor fill = shade_for_normal(bright);

    GPathInfo info = { face->n, face_pts };
    GPath *path = gpath_create(&info);
    graphics_context_set_fill_color(ctx, fill);
    gpath_draw_filled(ctx, path);
    graphics_context_set_stroke_color(ctx, outline);
    graphics_context_set_stroke_width(ctx, 1);
    gpath_draw_outline(ctx, path);
    gpath_destroy(path);

    /* Numeral. face->value is the polyhedron's baked label; combined
     * with the per-value rest rotation above, the face labeled
     * die->value lands dead-on at rest. */
    int32_t px = 0, py = 0;
    for (int k = 0; k < face->n; k++) {
      px += face_pts[k].x;
      py += face_pts[k].y;
    }
    px /= face->n;
    py /= face->n;

    bool is_active = (face->value == die->value);
    /* At rest, only the active face shows its numeral. */
    if (!is_rolling && !is_active) continue;

    /* Big "prominent" font only for the active face at rest. While
     * rolling, the active face is mid-tumble so the big font would
     * read awkwardly — every face uses the smaller side font, and the
     * highlight color is what makes the target value scannable. */
    bool    use_active_glyph = is_active && !is_rolling;
    GFont   fnt = use_active_glyph ? font_active  : font_side;
    int16_t bw  = use_active_glyph ? box_active_w : box_side_w;
    int16_t bh  = use_active_glyph ? box_active_h : box_side_h;

    char buf[4];
    snprintf(buf, sizeof(buf), "%d", (int)face->value);
    GColor text = is_active ? COLOR_NUMERAL_ACTIVE : COLOR_NUMERAL;
    graphics_context_set_text_color(ctx, text);
    graphics_draw_text(ctx, buf, fnt,
      GRect(px - bw / 2, py - bh / 2 - 1, bw, bh),
      GTextOverflowModeWordWrap, GTextAlignmentCenter, NULL);
  }
}
