/*
 * dice3d.c — procedural 3D polyhedron renderer.
 *
 * Fixed-point conventions:
 *   - Vertex coords live in int16_t with UNIT_FP (4096) representing 1.0.
 *     All polyhedra sit on a unit circumsphere, so coords are in
 *     [-UNIT_FP, +UNIT_FP].
 *   - sin_lookup / cos_lookup return [-TRIG_MAX_RATIO, +TRIG_MAX_RATIO]
 *     (= ±65536). After a rotation step we divide by TRIG_MAX_RATIO and
 *     fold back into int16_t.
 *
 * Screen coords:
 *   - 3D y is UP; Pebble screen y is DOWN. We negate y on projection.
 *   - 3D z is OUT of the screen toward the viewer.
 *
 * Culling and shading:
 *   - We compute the actual face plane normal via cross product of the
 *     first two edges. For D12 (regular dodecahedron), this matches the
 *     centroid direction, but for the D10 trapezohedron the kite faces
 *     are NOT symmetric around the polyhedron center — their centroids
 *     don't lie on the outward-normal axis — so centroid.z can disagree
 *     in sign with the actual normal.z. Using the real normal handles
 *     both polyhedra uniformly.
 *   - The cross-product normal's direction depends on vertex winding.
 *     We correct it by computing the dot product with the face centroid
 *     (which is guaranteed to be on the same side of origin as the
 *     outward direction, because the polyhedron is convex and centered
 *     at origin). If the dot is negative, the cross is pointing inward
 *     and we flip its sign.
 *   - After correction, n.z > 0 ⇔ face faces camera, and n · light is
 *     the lighting term.
 *
 * Winding (within faces):
 *   - Each face's vertices are listed in CCW order around the face's
 *     outward normal. gpath_draw_filled handles either winding for
 *     convex polygons identically, but the order must walk the
 *     perimeter — listing vertices that aren't adjacent on the face
 *     produces a self-intersecting polygon and visible gaps.
 *
 * Vertex / face tables for both polyhedra are generated by
 * tools/gen_dice.py. The script validates pentagon edge lengths, kite
 * planarity, opposite-pair value sums (D12), and perimeter ordering. Do
 * not hand-edit the tables; re-run the script.
 */

#include "dice3d.h"

#define UNIT_FP        4096   /* 1.0 in vertex fixed-point */
#define MAX_VERTS      20
#define MAX_FACE_VERTS 5

typedef struct {
  int16_t x, y, z;
} Vec3;

typedef struct {
  uint8_t v[MAX_FACE_VERTS]; /* CCW vertex indices, viewed from outside */
  uint8_t n;                 /* 5 for pentagonal face, 4 for kite */
  int8_t  value;             /* baked numeral for this face */
} Face;

/* --- D12: regular dodecahedron ------------------------------------------ */

/* Vertex and face tables below are generated by tools/gen_dice.py. Do
 * NOT edit by hand — re-run the script if anything needs to change. The
 * script validates pentagon edge lengths, opposite-pair value sums, and
 * face-vertex CCW ordering. (The hand-maintained tables previously here
 * had a transposed vertex ordering on face value 8 — value-8 rendered as
 * a self-intersecting polygon at certain tumble angles, visible as
 * angular gaps in the silhouette.)
 *
 * Pre-rotation: each table is rotated so face 0's centroid sits at +z at
 * rest_x = rest_y = rest_z = 0. The D12 rotation is Ry(-31.7175°). The
 * D10 rotation is Rx(+54.1526°) then Ry(-48.1293°). For the D12 (regular
 * pentagon faces) centroid-alignment and normal-alignment coincide; for
 * the D10 (asymmetric kite faces) centroid-alignment keeps the face
 * center on the die center where the numeral lives. */
static const Vec3 d12_verts[20] = {
  {   768,  2365,  3255 }, /*  0 */
  {  3255,  2365,  -768 }, /*  1 */
  {   768, -2365,  3255 }, /*  2 */
  {  3255, -2365,  -768 }, /*  3 */
  { -3255,  2365,   768 }, /*  4 */
  {  -768,  2365, -3255 }, /*  5 */
  { -3255, -2365,   768 }, /*  6 */
  {  -768, -2365, -3255 }, /*  7 */
  { -2012,  1462,  3255 }, /*  8 */
  {  2012,  1462, -3255 }, /*  9 */
  { -2012, -1462,  3255 }, /* 10 */
  {  2012, -1462, -3255 }, /* 11 */
  {  1243,  3826,   768 }, /* 12 */
  {  1243, -3826,   768 }, /* 13 */
  { -1243,  3826,  -768 }, /* 14 */
  { -1243, -3826,  -768 }, /* 15 */
  {  2487,     0,  3255 }, /* 16 */
  {  4023,     0,   768 }, /* 17 */
  { -4023,     0,  -768 }, /* 18 */
  { -2487,     0, -3255 }, /* 19 */
};

static const Face d12_faces[12] = {
  { { 10,  2, 16,  0,  8 }, 5,  1 },
  { { 19,  5,  9, 11,  7 }, 5, 12 },
  { {  9,  1, 17,  3, 11 }, 5,  2 },
  { {  6, 10,  8,  4, 18 }, 5, 11 },
  { {  4,  8,  0, 12, 14 }, 5,  3 },
  { {  7, 11,  3, 13, 15 }, 5, 10 },
  { { 14, 12,  1,  9,  5 }, 5,  4 },
  { { 15, 13,  2, 10,  6 }, 5,  9 },
  { {  0, 16, 17,  1, 12 }, 5,  5 },
  { { 19,  7, 15,  6, 18 }, 5,  8 },
  { {  3, 17, 16,  2, 13 }, 5,  6 },
  { { 18,  4, 14,  5, 19 }, 5,  7 },
};

/* --- D10: pentagonal trapezohedron ------------------------------------- */
static const Vec3 d10_verts[12] = {
  { -1786, -3320,  1601 }, /*  0: top apex    */
  {  1786,  3320, -1601 }, /*  1: bottom apex */
  {  2530,  -351,  3202 }, /*  2: upper[0] */
  { -1687,  1918,  3202 }, /*  3: upper[1] */
  { -3833,  1052,  -989 }, /*  4: upper[2] */
  {  -943, -1753, -3580 }, /*  5: upper[3] */
  {  2990, -2619,  -989 }, /*  6: upper[4] */
  {   943,  1753,  3580 }, /*  7: lower[0] */
  { -2990,  2619,   989 }, /*  8: lower[1] */
  { -2530,   351, -3202 }, /*  9: lower[2] */
  {  1687, -1918, -3202 }, /* 10: lower[3] */
  {  3833, -1052,   989 }, /* 11: lower[4] */
};

static const Face d10_faces[10] = {
  { {  0,  2,  7,  3 }, 4, 0 },
  { {  0,  3,  8,  4 }, 4, 1 },
  { {  0,  4,  9,  5 }, 4, 2 },
  { {  5, 10,  6,  0 }, 4, 3 },
  { {  6, 11,  2,  0 }, 4, 4 },
  { {  8,  3,  7,  1 }, 4, 5 },
  { {  4,  8,  1,  9 }, 4, 6 },
  { {  9,  1, 10,  5 }, 4, 7 },
  { {  1, 11,  6, 10 }, 4, 8 },
  { {  1,  7,  2, 11 }, 4, 9 },
};

/* --- Math --------------------------------------------------------------- */

static Vec3 rotate_vertex(Vec3 v, int32_t rx, int32_t ry, int32_t rz) {
  /* Rx -> Ry -> Rz. Each step divides products of (int16 * trig) by
   * TRIG_MAX_RATIO to fold the result back into the [-UNIT_FP, +UNIT_FP]
   * range. */
  int32_t x = v.x, y = v.y, z = v.z;

  int32_t cosx = cos_lookup(rx);
  int32_t sinx = sin_lookup(rx);
  int32_t y1 = (cosx * y - sinx * z) / TRIG_MAX_RATIO;
  int32_t z1 = (sinx * y + cosx * z) / TRIG_MAX_RATIO;
  /* x1 = x; */

  int32_t cosy = cos_lookup(ry);
  int32_t siny = sin_lookup(ry);
  int32_t x2 = ( cosy * x + siny * z1) / TRIG_MAX_RATIO;
  int32_t z2 = (-siny * x + cosy * z1) / TRIG_MAX_RATIO;
  /* y2 = y1; */

  int32_t cosz = cos_lookup(rz);
  int32_t sinz = sin_lookup(rz);
  int32_t x3 = (cosz * x2 - sinz * y1) / TRIG_MAX_RATIO;
  int32_t y3 = (sinz * x2 + cosz * y1) / TRIG_MAX_RATIO;

  return (Vec3){ .x = (int16_t)x3, .y = (int16_t)y3, .z = (int16_t)z2 };
}

static GPoint project(Vec3 v, GPoint center, int16_t radius) {
  /* Orthographic projection. y axis flips: 3D-y-up → screen-y-down. */
  return GPoint(
    center.x + (int16_t)((int32_t)v.x * radius / UNIT_FP),
    center.y - (int16_t)((int32_t)v.y * radius / UNIT_FP));
}

/* Light direction: upper-left, slightly toward camera. (-0.6, 0.6, 0.5)
 * in our fixed-point scale (4096 = 1.0). Pebble screen has y-down, but
 * dice3d works in 3D-y-up space and flips on projection, so a face whose
 * outward normal leans (-x, +y, +z) is the one pointing at the light. */
#define LIGHT_X (-2458)
#define LIGHT_Y  (2458)
#define LIGHT_Z  (2048)

/* Shading is n · light with n the un-normalized face normal. All faces
 * of a given polyhedron are congruent (regular pentagons for D12,
 * congruent kites for D10), so |n| is constant per polyhedron and we
 * can threshold the dot product directly. Thresholds are wide enough
 * to land sensibly for both polyhedra without per-type tuning. */
static GColor shade_for_normal(int64_t bright) {
#if defined(PBL_COLOR)
  if (bright >  20000000000LL) return GColorWhite;
  if (bright >              0) return GColorLightGray;
  if (bright > -20000000000LL) return GColorWindsorTan;
  return GColorBulgarianRose;
#else
  return (bright > 0) ? GColorWhite : GColorLightGray;
#endif
}

/* --- Public draw -------------------------------------------------------- */

void dice3d_draw(GContext *ctx, const Die *die) {
  const Vec3 *verts;
  const Face *faces;
  int n_verts, n_faces;

  if (die->type == DIE_HOUR) {
    verts   = d12_verts;
    faces   = d12_faces;
    n_verts = 20;
    n_faces = 12;
  } else {
    verts   = d10_verts;
    faces   = d10_faces;
    n_verts = 12;
    n_faces = 10;
  }

  /* Transform & project all vertices once. */
  Vec3   transformed[MAX_VERTS];
  GPoint projected  [MAX_VERTS];
  for (int i = 0; i < n_verts; i++) {
    transformed[i] = rotate_vertex(verts[i], die->rot_x, die->rot_y, die->rot_z);
    projected  [i] = project(transformed[i], die->center, die->radius);
  }

  /* Walk faces: cull back-facing via real face normal, shade by n·light,
   * draw filled + outlined, and track the front-most face for the numeral.
   *
   * Sliver suppression: an nz threshold can't distinguish "thin
   * protrusion at a polyhedron vertex" from "legitimate face slightly
   * tilted" — both can sit at ~85° tilt. Instead we cull on absolute
   * 2D projected area (shoelace formula). The protrusions project to
   * very small screen areas because they're geometrically tiny;
   * legitimate tilted faces project to larger areas because the face
   * is bigger. AREA_DOUBLE_MIN is in 2× pixel² units (we skip the /2
   * since we only need a threshold). */
  #define AREA_DOUBLE_MIN 80     /* faces projecting to <40 px² are culled */

  int     front_idx = -1;
  int32_t front_nz  = 0;
  GColor  outline   = GColorBlack;

  for (int f = 0; f < n_faces; f++) {
    const Face *face = &faces[f];

    /* 3D centroid — used to ensure the cross-product normal points
     * outward, since the centroid is always on the same side of origin
     * as the outward-facing direction for a convex polyhedron centered
     * at origin. */
    int32_t cx = 0, cy = 0, cz = 0;
    for (int k = 0; k < face->n; k++) {
      cx += transformed[face->v[k]].x;
      cy += transformed[face->v[k]].y;
      cz += transformed[face->v[k]].z;
    }
    cx /= face->n;
    cy /= face->n;
    cz /= face->n;

    /* Face plane normal: cross product of two edges sharing vertex v[0]. */
    int32_t e1x = transformed[face->v[1]].x - transformed[face->v[0]].x;
    int32_t e1y = transformed[face->v[1]].y - transformed[face->v[0]].y;
    int32_t e1z = transformed[face->v[1]].z - transformed[face->v[0]].z;
    int32_t e2x = transformed[face->v[2]].x - transformed[face->v[0]].x;
    int32_t e2y = transformed[face->v[2]].y - transformed[face->v[0]].y;
    int32_t e2z = transformed[face->v[2]].z - transformed[face->v[0]].z;

    int32_t nx = e1y * e2z - e1z * e2y;
    int32_t ny = e1z * e2x - e1x * e2z;
    int32_t nz = e1x * e2y - e1y * e2x;

    /* Winding correction: flip if normal points inward. */
    int64_t outward = (int64_t)nx * cx + (int64_t)ny * cy + (int64_t)nz * cz;
    if (outward < 0) {
      nx = -nx; ny = -ny; nz = -nz;
    }

    /* Backface cull (true camera-facing test). */
    if (nz <= 0) continue;

    /* Sliver cull: projected 2D area via shoelace. Both winding
     * directions yield the same |area|, so this is winding-independent. */
    GPoint face_pts[MAX_FACE_VERTS];
    for (int k = 0; k < face->n; k++) face_pts[k] = projected[face->v[k]];
    int32_t area_2x = 0;
    for (int k = 0; k < face->n; k++) {
      GPoint a = face_pts[k];
      GPoint b = face_pts[(k + 1) % face->n];
      area_2x += (int32_t)a.x * b.y - (int32_t)b.x * a.y;
    }
    if (area_2x < 0) area_2x = -area_2x;
    if (area_2x < AREA_DOUBLE_MIN) continue;

    if (nz > front_nz) {
      front_nz  = nz;
      front_idx = f;
    }

    int64_t bright = (int64_t)nx * LIGHT_X
                   + (int64_t)ny * LIGHT_Y
                   + (int64_t)nz * LIGHT_Z;

    GPathInfo info = { face->n, face_pts };
    GPath *path = gpath_create(&info);
    graphics_context_set_fill_color(ctx, shade_for_normal(bright));
    gpath_draw_filled(ctx, path);
    graphics_context_set_stroke_color(ctx, outline);
    graphics_context_set_stroke_width(ctx, 1);
    gpath_draw_outline(ctx, path);
    gpath_destroy(path);
  }

  if (front_idx < 0) return;

  /* Numeral on the front face. Centroid in screen space. */
  const Face *front = &faces[front_idx];
  int32_t cx = 0, cy = 0;
  for (int k = 0; k < front->n; k++) {
    cx += projected[front->v[k]].x;
    cy += projected[front->v[k]].y;
  }
  cx /= front->n;
  cy /= front->n;

  /* During a tumble (die->tumbling), show whatever face is currently
   * front-facing — the baked-numeral flicker reads as the die turning.
   * At rest, show the actual target value so settled rendering through
   * this same path lands on the correct number regardless of which face
   * the polyhedron happens to present dead-on. Step 3 of Phase 2.5 routes
   * the settled draw here too, which is what makes this conditional load-
   * bearing. */
  int displayed = die->tumbling ? front->value : die->value;
  char buf[6];
  if (die->type == DIE_TENS) {
    snprintf(buf, sizeof(buf), "%d0", displayed);
  } else {
    snprintf(buf, sizeof(buf), "%d", displayed);
  }

  GFont font = (die->type == DIE_HOUR)
    ? fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD)
    : fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD);

  int16_t box_w = (die->type == DIE_HOUR) ? 40 : 32;
  int16_t box_h = (die->type == DIE_HOUR) ? 26 : 22;
  graphics_context_set_text_color(ctx, GColorBlack);
  graphics_draw_text(ctx, buf, font,
    GRect(cx - box_w / 2, cy - box_h / 2 - 1, box_w, box_h),
    GTextOverflowModeWordWrap, GTextAlignmentCenter, NULL);
}
